/**
 * @file TrafficContribution.h
 * @brief Building traffic contribution calculation for Epic 7 (Ticket E7-012)
 *
 * Defines:
 * - TrafficContributionConfig: Configurable base traffic values per zone type
 * - calculate_traffic_contribution(): Inline function to compute per-building
 *   traffic generation based on zone type, occupancy, and building level
 *
 * Zone types use canonical alien terminology per /docs/canon/terminology.yaml:
 * - habitation (residential)
 * - exchange (commercial)
 * - fabrication (industrial)
 */

#pragma once

#include <cstdint>

namespace sims3000 {
namespace transport {

/**
 * @struct TrafficContributionConfig
 * @brief Base traffic contribution per zone type per tick.
 *
 * These values represent flow units generated per tick, scaled by
 * the building's occupant ratio and level.
 */
struct TrafficContributionConfig {
    uint32_t habitation_base  = 2;    ///< flow/tick per occupant ratio (residential)
    uint32_t exchange_base    = 5;    ///< flow/tick per occupant ratio (commercial)
    uint32_t fabrication_base = 3;    ///< flow/tick per occupant ratio (industrial)
};

/**
 * @brief Calculate traffic contribution for a building.
 *
 * Computes the traffic flow generated by a single building per tick,
 * based on its zone type, occupancy level, and building level.
 *
 * Formula: (base * occupant_ratio * level) / 255
 *
 * The occupant_ratio is a uint8_t (0-255) representing 0% to 100% occupancy.
 * The level multiplier provides linear scaling (level 2 = 2x, level 3 = 3x).
 *
 * @param zone_type     Zone type: 0=habitation, 1=exchange, 2=fabrication
 * @param occupant_ratio Occupancy level 0-255 (0=empty, 255=full)
 * @param level         Building level (1-3)
 * @param config        Traffic contribution configuration (optional, uses defaults)
 * @return Traffic flow units generated per tick. Returns 0 for invalid zone types.
 */
inline uint32_t calculate_traffic_contribution(
    uint8_t zone_type,
    uint8_t occupant_ratio,
    uint8_t level,
    const TrafficContributionConfig& config = TrafficContributionConfig{})
{
    uint32_t base = 0;
    switch (zone_type) {
        case 0: base = config.habitation_base; break;
        case 1: base = config.exchange_base; break;
        case 2: base = config.fabrication_base; break;
        default: return 0;
    }
    // Scale by occupant ratio (0-255 mapped to 0.0-1.0) and level
    return (base * occupant_ratio * level) / 255;
}

} // namespace transport
} // namespace sims3000
